// full list at https://emojipedia.org/nature/
var emojis={All:{
  Grapes:"🍇",Melon:"🍈",Watermelon:"🍉",Tangerine:"🍊",Lemon:"🍋",Banana:"🍌",Pineapple:"🍍",
  Apple:"🍎",Apple:"🍏",Pear:"🍐",Peach:"🍑",Cherries:"🍒",
  Strawberry:"🍓",Kiwi:"🥝",Tomato:"🍅",Coconut:"🥥",Avocado:"🥑",Eggplant:"🍆",
  Potato:"🥔",Carrot:"🥕",Corn:"🌽",Pepper:"🌶",Cucumber:"🥒",Broccoli:"🥦",
  Mushroom:"🍄",Peanuts:"🥜",Chestnut:"🌰",Bread:"🍞",Croissant:"🥐",Baguette:"🥖",
  Pretzel:"🥨",Pancakes:"🥞",Cheese:"🧀",Meat:"🍖",Poultry:"🍗",Meat:"🥩",Bacon:"🥓",Hamburger:"🍔",
  Fries:"🍟",Pizza:"🍕",
  "HotDog":"🌭",
  Sandwich:"🥪",Taco:"🌮",Burrito:"🌯",Cooking:"🍳",Pot:"🍲",Bowl:"🥣",
  Salad:"🥗",Popcorn:"🍿",Can:"🥫",Bento:"🍱",Cracker:"🍘",Rice:"🍚",Curry:"🍛",Bowl:"🍜",Spaghetti:"🍝",
  Potato:"🍠",Sushi:"🍣",Shrimp:"🍤",Dumpling:"🥟",Cookie:"🥠",Box:"🥡","IceCream":"🍦",
  Doughnut:"🍩",Cookie:"🍪",Cake:"🎂",Shortcake:"🍰",Pie:"🥧",Chocolate:"🍫",
  Candy:"🍬",Lollipop:"🍭",Custard:"🍮",Honey:"🍯",Bottle:"🍼",
  Milk:"🥛",Beverage:"☕",Teacup:"🍵",Sake:"🍶",Cork:"🍾",Wine:"🍷",Cocktail:"🍸",Drink:"🍹",Beer:"🍺",
  Mug:"🍻",Glasses:"🥂",Glass:"🥃",Straw:"🥤",Chopsticks:"🥢",Plate:"🍽",Fork:"🍴",Spoon:"🥄",
  Monkey:"🙉",Collision:"💥",Droplets:"💦",Dizzy:"💫",Monkey:"🐵",Monkey:"🐒",Gorilla:"🦍",Dog:"🐶",Dog:"🐕",
  Poodle:"🐩",Wolf:"🐺",Fox:"🦊",Cat:"🐱",Cat:"🐈",Lion:"🦁",Tiger:"🐯",Tiger:"🐅",Leopard:"🐆",
  Horse:"🐴",Horse:"🐎",Unicorn:"🦄",Zebra:"🦓",Cow:"🐮",Ox:"🐂",Buffalo:"🐃",Cow:"🐄",Pig:"🐷",
  Pig:"🐖",Boar:"🐗",Pig:"🐽",Ram:"🐏",Ewe:"🐑",Goat:"🐐",Camel:"🐪",Camel:"🐫",Giraffe:"🦒",
  Elephant:"🐘",Rhinoceros:"🦏",Mouse:"🐭",Mouse:"🐁",Rat:"🐀",Hamster:"🐹",Rabbit:"🐰",
  Rabbit:"🐇",Chipmunk:"🐿",Hedgehog:"🦔",Bat:"🦇",Bear:"🐻",Koala:"🐨",Panda:"🐼",Paw:"🐾",
  Turkey:"🦃",Chicken:"🐔",Rooster:"🐓",Chick:"🐣",Chick:"🐤",Chick:"🐥",Bird:"🐦",Penguin:"🐧",Dove:"🕊",
  Eagle:"🦅",Duck:"🦆",Owl:"🦉",Frog:"🐸",Crocodile:"🐊",Turtle:"🐢",Lizard:"🦎",Snake:"🐍",Dragon:"🐲",
  Dragon:"🐉",Sauropod:"🦕",Trex:"🦖",Whale:"🐳",Whale:"🐋",Dolphin:"🐬",Fish:"🐟",Fish:"🐠",Blowfish:"🐡",
  Shark:"🦈",Octopus:"🐙",Shell:"🐚",Crab:"🦀",Shrimp:"🦐",Squid:"🦑",Snail:"🐌",Butterfly:"🦋",
  Bug:"🐛",Ant:"🐜",
  Honeybee:"🐝",
  Bee:"🐝",
  Beetle:"🐞",Cricket:"🦗",Spider:"🕷",Web:"🕸",Scorpion:"🦂",
  Bouquet:"💐",Blossom:"🌸",Rosette:"🏵",Rose:"🌹",Flower:"🥀",Hibiscus:"🌺",Flower:"🌼",Tulip:"🌷",
  Seedling:"🌱",Tree:"🌲",Deciduous:"🌳",Palm:"🌴",Cactus:"🌵",Rice:"🌾",Herb:"🌿",Shamrock:"☘",
  Clover:"🍀",Maple:"🍁",Leaf:"🍂",Leaf:"🍃",Mushroom:"🍄",Chestnut:"🌰",Moon:"🌕",Moon:"🌜",Sun:"🌞",
  Star:"⭐",Cloud:"⛅",Tornado:"🌪",
  Rainbow:"🌈",
  //Umbrella:"☂",
  Drops:"☔",
  Snowman:"⛄",Comet:"☄",Fire:"🔥",Droplet:"💧",
  Tree:"🎄",Sparkles:"✨",Tanabata:"🎋",Pine:"🎍",Baby:"👶",Angel:"👼",SantaClaus:"🎅",Elf:"🧝",
  Socks:"🧦",Deer:"🦌",Cookie:"🍪",Milk:"🥛",Wine:"🍷",Fork:"🍴",Church:"⛪",Star:"🌟",Snowflake:"❄",
  Snowman:"⛄",Fire:"🔥",Tree:"🎄",Gift:"🎁",Bell:"🔔",Notes:"🎶",Candle:"🕯",Smiling:"😁",Snowboarder:"🏂",
  Evergreen:"🌲",Mountain:"🏔",
  Wind:"🌬",
  //Umbrella:"🌂",
  Rain:"☔",Snowflake:"❄",Snowman:"⛄",Skis:"🎿",Horse:"🏇",Skier:"⛷",Snowboarder:"🏂",
  Surfing:"🏄",Rowing:"🚣",Boat:"🚣",Swimming:"🏊",Bouncing:"⛹",Weights:"🏋",Biking:"🚴",
  Wrestling:"🤼",
  Handball:"🤾",Juggling:"🤹",Circus:"🎪",Ribbon:"🎗",Ticket:"🎫",Medal:"🎖",
  Trophy:"🏆",Medal:"🏅",Soccer:"⚽",Basketball:"🏀",Volleyball:"🏐",Football:"🏈",Rugby:"🏉",Tennis:"🎾",
  Bowling:"🎳",Cricket:"🏏",Hockey:"🏑",Hockey:"🏒",
  "PingPong":"🏓",
  Badminton:"🏸",Boxing:"🥊",
  Skating:"⛸",
  Fishing:"🎣",
  Skis:"🎿",Sled:"🛷",Pool:"🎱",Dice:"🎲",Palette:"🎨",Score:"🎼",Microphone:"🎤",Headphone:"🎧",
  Saxophone:"🎷",Guitar:"🎸",Keyboard:"🎹",Trumpet:"🎺",Violin:"🎻",Drum:"🥁",Clapper:"🎬",Bow:"🏹",
  Rowing:"🚣",Racing:"🏎",Motorcycle:"🏍",Mountain:"🏔",Fountain:"⛲",Volcano:"🌋",Fuji:"🗻",
  Camping:"🏕",Beach:"🏖",Desert:"🏜",Island:"🏝",
  Stadium:"🏟",Building:"🏛",Construction:"🏗",Houses:"🏘",
  House:"🏠",
  Office:"🏢",
  "PostOffice":"🏤",
  Hospital:"🏥",Bank:"🏦",Hotel:"🏨",Store:"🏪",School:"🏫",Factory:"🏭",Castle:"🏰",Wedding:"💒",
  Liberty:"🗽",Church:"⛪",Mosque:"🕌",Synagogue:"🕍",Kaaba:"🕋",Tent:"⛺",
  Carousel:"🎠","Wheel":"🎡",Roller:"🎢",
  Locomotive:"🚂",Railway:"🚃",Train:"🚄",Train:"🚅",Train:"🚆",Metro:"🚇",Rail:"🚈",
  Tram:"🚊",Monorail:"🚝",Railway:"🚞",Tram:"🚋",Bus:"🚌",Trolleybus:"🚎",Minibus:"🚐",Ambulance:"🚑",
  Fire:"🚒",Police:"🚓",Taxi:"🚕",Taxi:"🚖",Automobile:"🚗",Automobile:"🚘",Truck:"🚚",Lorry:"🚛",Tractor:"🚜",
  Bicycle:"🚲",Scooter:"🛴",Scooter:"🛵",
  Fuel:"⛽",Light:"🚦",Construction:"🚧",Anchor:"⚓",Sailboat:"⛵",Speedboat:"🚤",Ship:"🛳",Ferry:"⛴",Boat:"🛥",
  Ship:"🚢",Airplane:"🛩",Seat:"💺",Helicopter:"🚁",Cableway:"🚠",Tramway:"🚡",Satellite:"🛰",Rocket:"🚀",
  Saucer:"🛸",
  //Umbrella:"⛱",
  Yen:"💴",Dollar:"💵",Euro:"💶",Pound:"💷",Moai:"🗿",
  "Smiling":"😀","Joy":"😂","Laughing":"🤣","Sweat":"😅","Squinting":"😆","Winking":"😉",
  Savoring:"😋",Sunglasses:"😎",Kiss:"😘",Hugging:"🤗",Thinking:"🤔",Eyebrow:"🤨",Rolling:"🙄",Smirking:"😏",
  Persevering:"😣",Relieved:"😥",Sleepy:"😪",Tired:"😫",Sleeping:"😴",Relieved:"😌",Tongue:"😛",
  Drooling:"🤤",Pensive:"😔",Confused:"😕",Astonished:"😲",Disappointed:"😞",Worried:"😟",
  Ogre:"👹",Goblin:"👺",Skull:"💀",Ghost:"👻",Alien:"👽",Robot:"🤖",Poo:"💩",
  Biceps:"💪",Index:"👈",Horns:"🤘",Hand:"✋",OK:"👌",Thumbs:"👍",Fist:"✊",Waving:"👋",Clapping:"👏",
  Handshake:"🤝",Nail:"💅",Ear:"👂",Nose:"👃",Footprints:"👣",Eyes:"👀",Eye:"👁",Brain:"🧠",Tongue:"👅",Mouth:"👄",
  Glasses:"👓",Sunglasses:"🕶",Necktie:"👔",TShirt:"👕",Jeans:"👖",Scarf:"🧣",Gloves:"🧤",Coat:"🧥",Socks:"🧦",
  Dress:"👗",Kimono:"👘",Bikini:"👙",Purse:"👛",Handbag:"👜",Backpack:"🎒",Shoe:"👞",Shoe:"👟",
  Sandal:"👡",Boot:"👢",Crown:"👑",Hat:"👒",Cap:"🎓",Helmet:"⛑",Lipstick:"💄",Ring:"💍",
  //Umbrella:"🌂",
  Briefcase:"💼",
  Bath:"🛀",Bed:"🛌",Bomb:"💣",Hole:"🕳",Bags:"🛍",Gem:"💎",Knife:"🔪",
  Amphora:"🏺",Map:"🗺",Drum:"🛢",Bell:"🛎",Hourglass:"⌛",Watch:"⌚",Alarm:"⏰",Stopwatch:"⏱",Timer:"⏲",
  Thermometer:"🌡",
  Umbrella:"⛱",
  Balloon:"🎈",Popper:"🎉",Dolls:"🎎",Ribbon:"🎀",Gift:"🎁",Crystal:"🔮",
  Joystick:"🕹",Picture:"🖼",Microphone:"🎙",Radio:"📻",Phone:"📱",Telephone:"📞",Pager:"📟",Fax:"📠",
  Battery:"🔋",Plug:"🔌",Laptop:"💻",Computer:"🖥",Printer:"🖨",Keyboard:"⌨",Mouse:"🖱",Trackball:"🖲",Disk:"💽",
  Floppy:"💾",DVD:"📀",Camera:"🎥",Projector:"📽",Television:"📺",Camera:"📷",
  Videocassette:"📼",
  Magnifying:"🔍",Candle:"🕯",Bulb:"💡",Flashlight:"🔦",Lantern:"🏮",Notebook:"📔",Book:"📕",Books:"📚",Notebook:"📓",
  Page:"📃",Scroll:"📜",Newspaper:"🗞",Bookmark:"🔖",Label:"🏷",Money:"💰",
  CreditCard:"💳",Envelope:"📩",Package:"📦",Mailbox:"📫",Postbox:"📮",Pencil:"✏",Pen:"🖊",Paintbrush:"🖌",Crayon:"🖍",
  Memo:"📝",
  Folder:"📁",Calendar:"📅",Notepad:"🗒",Chart:"📈",BarChart:"📊",Clipboard:"📋",
  Pushpin:"📌",
  Paperclip:"📎",Ruler:"📏",Scissors:"✂",Cabinet:"🗄",Wastebasket:"🗑",Locked:"🔒",Unlocked:"🔓",
  Key:"🔑",Hammer:"🔨",Pick:"⛏",Dagger:"🗡",Pistol:"🔫",Shield:"🛡",Wrench:"🔧",Bolt:"🔩",Gear:"⚙",Clamp:"🗜",
  Scale:"⚖",Link:"🔗",Chains:"⛓",Alembic:"⚗",Microscope:"🔬",Telescope:"🔭",Satellite:"📡",Syringe:"💉",Pill:"💊",
  Door:"🚪",Bed:"🛏",Couch:"🛋",Toilet:"🚽",Shower:"🚿",Bathtub:"🛁",Cigarette:"🚬",
  Moai:"🗿",Flag:"🏁",
  Golfing:"🏌"
  }
};

function hexCodeFromEmoji(emoji)
{
  if (emoji === undefined)
    return hexCodeFromEmoji(emojis.All.Smiling);

  var code = emoji.charCodeAt(0);
  if (emoji.length > 2)
    return hexCodeFromEmoji(emojis.All.Smiling);
  if (emoji.length === 2)
  {
    code = (0x10000
            | ((emoji.charCodeAt(0) - 0xD800) << 10)
            | (emoji.charCodeAt(1) - 0xDC00));
  }
  var hexcode = code.toString(16);
  return hexcode;
}